apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudmart-prod

resources:
  - ../../configmap.yaml
  - ../../network-policies.yml
  - ../../frontend/deployment.yml
  - ../../frontend/service.yml
  - ../../frontend/ingress.yaml
  - ../../product-service/deployment.yml
  - ../../product-service/service.yml
  - ../../product-service/service-account.yml
  - ../../product-service/hpa.yml
  - ../../order-service/deployment.yml
  - ../../order-service/service.yml
  - ../../order-service/service-account.yml
  - ../../order-service/hpa.yml
  - ../../user-service/deployment.yml
  - ../../user-service/service.yml
  - ../../notification-service/deployment.yml
  - ../../notification-service/service.yml
  - ../../notification-service/service-account.yml
