apiVersion: v1
kind: Namespace
metadata:
  name: cloudmart-prod
  labels:
    app: cloudmart
    environment: production
    network/default-deny: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudmart-staging
  labels:
    app: cloudmart
    environment: staging
    network/default-deny: "true"
